# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # # machine #1 a debian 8 machine
  # config.vm.define "serverA" do |server|
  #   server.vm.box = "debian/stretch64"
  #   server.vm.synced_folder "shared", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false
  #
  #   # and do provisioning
  #   server.vm.provision "ansible" do |ansible|
  #     ansible.playbook = "test.yml"
  #   end
  # end

  # machine #2 a debian 8 machine - the logserver
  config.vm.define "srv-mon" do |serverB|
    serverB.vm.box = "debian/stretch64"
    serverB.vm.synced_folder "shared", "/vagrant", type: "9p"

    # and do provisioning
    serverB.vm.provision "ansible" do |ansible|
      ansible.playbook = "test.yml"
      ansible.groups = {
            "servers" => ["srv-mon"]
      }
    end
  end

  # start this on the localhost, not a remote kvm host
  config.vm.provider :libvirt do |libvirt|
    libvirt.host = ""
    libvirt.memory = 1024
  end

end
